-- auto Generated on 2019-07-20
-- DROP TABLE IF EXISTS redis;
CREATE TABLE redis(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
	id VARCHAR (50) NOT NULL COMMENT 'id',
    `age` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'age',
    `sex` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'sex',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	age INT (11) NOT NULL DEFAULT 1 COMMENT 'age',
	sex VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'sex',
	INDEX(id),
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'redis';


ALTER TABLE redis
ADD COLUMN `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
ADD COLUMN `age` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'age' AFTER `name`,
ADD COLUMN `sex` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'sex' AFTER `age`;
